services:
  fmc:
    build:
      dockerfile: ./Dockerfile
    image: fmc
    container_name: fmc
    ports:
      - 6010:6010
      - 6011:6011
      - 6012:6012
      - 6013:6013
      - 6014:6014
      - 6015:6015
    develop:
      watch:
        - action: sync
          path: ./apps/angular
          target: /app/apps/angular
        - action: sync
          path: ./apps/css
          target: /app/apps/css
        - action: sync
          path: ./apps/host
          target: /app/apps/host
        - action: sync
          path: ./apps/javascript
          target: /app/apps/javascript
        - action: sync
          path: ./apps/react
          target: /app/apps/react
        - action: sync
          path: ./apps/vue
          target: /app/apps/vue
        - action: sync
          path: ./shared
          target: /app/shared
        - action: rebuild
          path: ./apps/angular/package.json
        - action: rebuild
          path: ./apps/css/package.json
        - action: rebuild
          path: ./apps/host/package.json
        - action: rebuild
          path: ./apps/javascript/package.json
        - action: rebuild
          path: ./apps/react/package.json
        - action: rebuild
          path: ./apps/vue/package.json
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
