export const connectedTwoWords = [
  ['India', 'New Delhi'],
  ['Indonesia', 'Jakarta'],
  ['Iran', 'Tehran'],
  ['Iraq', 'Baghdad'],
  ['Ireland', 'Dublin'],
  ['Israel', 'Jerusalem'],
  ['Italy', 'Rome'],
  ['Jamaica', 'Kingston'],
  ['Japan', 'Tokyo'],
  ['Jordan', 'Amman'],
  ['Kazakhstan', 'Nur-Sultan'],
  ['Kenya', 'Nairobi'],
  ['Kiribati', 'South Tarawa'],
  ['Kuwait', 'Kuwait City'],
  ['Kyrgyzstan', 'Bishkek'],
  ['Laos', 'Vientiane'],
  ['Latvia', 'Riga'],
  ['Lebanon', 'Beirut'],
  ['Lesotho', 'Maseru'],
  ['Liberia', 'Monrovia'],
  ['Libya', 'Tripoli'],
  ['Liechtenstein', 'Vaduz'],
  ['Lithuania', 'Vilnius'],
  ['Madagascar', 'Antananarivo'],
  ['Malawi', 'Lilongwe'],
  ['Malaysia', 'Kuala Lumpur'],
  ['Maldives', 'Malé'],
  ['Mali', 'Bamako'],
  ['Malta', 'Valletta'],
  ['Mauritania', 'Nouakchott'],
  ['Mauritius', 'Port Louis'],
  ['Mexico', 'Mexico City'],
];

export const connectedThreeWords = [
  ['Basil', 'Thyme', 'Rosemary'],
  ['Latte', 'Cappuccino', 'Espresso'],
  ['Octopus', 'Dolphin', 'Seahorse'],
  ['Beach', 'Mountain', 'Forest'],
  ['Paintbrush', 'Canvas', 'Palette'],
  ['Tent', 'Sleeping Bag', 'Backpack'],
  ['Rock', 'Pop', 'Jazz'],
  ['Running', 'Yoga', 'Dancing'],
  ['Volcano', 'Canyon', 'Ocean'],
  ['Phone', 'Email', 'Letter'],
  ['Flood', 'Earthquake', 'Hurricane'],
  ['Sight', 'Smell', 'Taste'],
  ['Past', 'Present', 'Future'],
  ['Literature', 'History', 'Biology'],
  ['Spring', 'Summer', 'Autumn'],
];

export const connectedFourWords = [
  ['Cinnamon', 'Nutmeg', 'Ginger', 'Allspice'],
  ['Paperclips', 'Stapler', 'Sticky Notes', 'Highlighter'],
  ['Guitar', 'Drums', 'Piano', 'Violin'],
  ['Mercury', 'Venus', 'Earth', 'Mars'],
  ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
  ['Black', 'White', 'Grey', 'Navy Blue'],
  ['Skiing', 'Snowboarding', 'Ice Skating', 'Hockey'],
  ['Sun', 'Rain', 'Wind', 'Snow'],
  ['Hand', 'Foot', 'Ear', 'Eye'],
  ['Apple', 'Orange', 'Banana', 'Grape'],
  ['Math', 'English', 'Science', 'History'],
  ['Car', 'Bus', 'Train', 'Airplane'],
];

export const connectedWords = new Map([
  [2, connectedTwoWords],
  [3, connectedThreeWords],
  [4, connectedFourWords],
]);
