/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChallengeGrid {
    }
}
declare global {
    interface HTMLChallengeGridElement extends Components.ChallengeGrid, HTMLStencilElement {
    }
    var HTMLChallengeGridElement: {
        prototype: HTMLChallengeGridElement;
        new (): HTMLChallengeGridElement;
    };
    interface HTMLElementTagNameMap {
        "challenge-grid": HTMLChallengeGridElement;
    }
}
declare namespace LocalJSX {
    interface ChallengeGrid {
    }
    interface IntrinsicElements {
        "challenge-grid": ChallengeGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "challenge-grid": LocalJSX.ChallengeGrid & JSXBase.HTMLAttributes<HTMLChallengeGridElement>;
        }
    }
}
