export const challenges = [
  {
    title: 'Counter',
    link: 'counter',
    difficulty: 'easy',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Guess the number',
    link: 'guess-the-number',
    difficulty: 'easy',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'String transformers',
    link: 'string-transformers',
    difficulty: 'easy',
    developer: 'sadanandpai',
    tags: [],
    isNew: true,
  },
  {
    title: 'Telephone formatter',
    link: 'telephone-formatter',
    difficulty: 'easy',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Light & Dark mode',
    link: 'light-dark-mode',
    difficulty: 'easy',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Skeleton Loader',
    link: 'skeleton-loader',
    difficulty: 'easy',
    developer: 'sahankatta',
    tags: [],
    isNew: true,
  },
  {
    title: 'Accordion',
    link: 'accordion',
    difficulty: 'easy',
    developer: 'rashidtvmr',
    isNew: true,
    tags: [],
  },
  {
    title: 'Navigation Bar',
    link: 'navigation-bar',
    difficulty: 'easy',
    developer: 'christian-lee1398',
    tags: [],
    isNew: true,
  },
  {
    title: 'Multi Typing',
    link: 'multi-typing',
    difficulty: 'easy',
    developer: 'noorulaink00',
    tags: [],
  },
  {
    title: 'Dialog Popup',
    link: 'dialog-popup',
    difficulty: 'easy',
    developer: 'sahankatta',
    tags: [],
    isNew: true,
  },
  {
    title: 'Meme Generator',
    link: 'meme-generator',
    difficulty: 'medium',
    developer: 'noorulaink00',
    tags: [],
    isNew: true,
  },
  {
    title: 'Toast Popup',
    link: 'toast-popup',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'CSS Shapes',
    link: 'css-shapes',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Column Table',
    link: 'column-table',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
    isNew: true,
  },
  {
    title: 'Password Strength',
    link: 'password-strength',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Star Rating',
    link: 'star-rating',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Star Rating Display',
    link: 'star-rating-display',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
    isNew: true,
  },
  {
    title: 'Pixel Art',
    link: 'pixel-art',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Color Spotter',
    link: 'color-spotter',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Todo List',
    link: 'todo-list',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Transfer List',
    link: 'transfer-list',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Lift Simulation',
    link: 'lift-simulation',
    difficulty: 'medium',
    developer: 'gauravsinhaweb',
    tags: [],
    isNew: true,
  },
  {
    title: 'Tic-Tac-Toe',
    link: 'tic-tac-toe',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Chess board',
    link: 'chess-board',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Chips Input',
    link: 'chips-input',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Password Generator',
    link: 'password-generator',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Analog Clock',
    link: 'analog-clock',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Drag and Drop Puzzle',
    link: 'drag-and-drop-puzzle',
    difficulty: 'medium',
    developer: 'noorulaink00',
    tags: [],
    isNew: true,
  },
  {
    title: 'Basic calculator',
    link: 'basic-calculator',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Match Pair',
    link: 'match-pair',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Typing Speed Test',
    link: 'typing-speed-test',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Countdown Timer',
    link: 'count-down-timer',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'OTP Input',
    link: 'otp-input',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
    isNew: true,
  },
  {
    title: 'Quiz App',
    link: 'quiz-app',
    difficulty: 'medium',
    developer: 'Kei-K23',
    tags: [],
    isNew: true,
  },
  {
    title: 'Snake Game',
    link: 'snake-game',
    difficulty: 'medium',
    developer: 'Kei-K23',
    tags: [],
    isNew: true,
  },
  {
    title: 'Hangman Game',
    link: 'hangman-game',
    difficulty: 'medium',
    developer: 'Kei-K23',
    tags: [],
    isNew: true,
  },
  {
    title: 'Area Selector',
    link: 'area-selector',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: '25-5 Clock',
    link: '25-5-clock',
    difficulty: 'medium',
    developer: 'caesar003',
    tags: [],
    isNew: true,
  },
  {
    title: 'Carousel',
    link: 'carousel',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Calendar',
    link: 'calendar',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  { title: 'Stepper', link: '#' },
  {
    title: 'Progress Bar',
    link: 'progress-bar',
    difficulty: 'medium',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Paginator',
    link: 'paginator',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Connect Four',
    link: 'connect-four',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Comment box',
    link: 'comment-box',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'JSON Creator',
    link: 'json-creator',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Array methods',
    link: 'array-methods',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Typeahead / Autocomplete (offline)',
    link: 'type-ahead',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Typeahead / Autocomplete (online)',
    link: 'type-ahead-online',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
  },
  { title: 'Emoji Editor', link: '#' },
  { title: 'Sort Table', link: '#' },
  { title: 'Infinite Scroll', link: '#' },
];
