export const challenges = [
  { title: 'Counter', link: 'counter' },
  { title: 'Guess the number', link: 'guess-the-number' },
  { title: 'String transformers', link: 'string-transformers', isNew: true },
  { title: 'Telephone formatter', link: 'telephone-formatter' },
  { title: 'Light & Dark mode', link: 'light-dark-mode' },
  { title: 'Toast Popup', link: 'toast-popup' },
  { title: 'CSS Shapes', link: 'css-shapes' },
  { title: 'Password Strength', link: 'password-strength' },
  { title: 'Star Rating', link: 'star-rating' },
  { title: 'Pixel Art', link: 'pixel-art' },
  { title: 'Color Spotter', link: 'color-spotter' },
  { title: 'Todo List', link: 'todo-list' },
  { title: 'Transfer List', link: 'transfer-list' },
  { title: 'Tic-Tac-Toe', link: 'tic-tac-toe' },
  { title: 'Chess board', link: 'chess-board' },
  { title: 'Skeleton Loader', link: '#' },
  { title: 'Chips Input', link: 'chips-input' },
  { title: 'Password Generator', link: 'password-generator' },
  { title: 'Analog Clock', link: 'analog-clock' },
  { title: 'Drag and Drop Puzzle', link: 'drag-and-drop-puzzle', isNew: true },
  { title: 'Basic calculator', link: 'basic-calculator', isNew: true },
  { title: 'Navigation Bar', link: '#' },
  { title: 'Match Pair', link: 'match-pair', isNew: true },
  { title: 'Typing Speed Test', link: 'typing-speed-test' },
  { title: 'Countdown Timer', link: 'count-down-timer' },
  { title: 'OTP Input', link: 'otp-input', isNew: true },
  { title: 'Area Selector', link: 'area-selector' },
  { title: 'Carousel', link: 'carousel' },
  { title: 'Calendar', link: 'calendar' },
  { title: 'Progress Bar', link: 'progress-bar' },
  { title: 'Paginator', link: 'paginator' },
  { title: 'Connect Four', link: 'connect-four', isNew: true },
  { title: 'Comment box', link: 'comment-box' },
  { title: 'JSON Creator', link: 'json-creator' },
  { title: 'Typeahead / Autocomplete (offline)', link: 'type-ahead', isNew: true },
  { title: 'Typeahead / Autocomplete (online)', link: 'type-ahead-online', isNew: true },
  { title: 'Array methods', link: 'array-methods' },
  { title: 'Stepper', link: '#' },
  { title: 'Accordion', link: '#' },
  { title: 'Dialog Popup', link: '#' },
  { title: 'Sort Table', link: '#' },
  { title: 'Emoji Editor', link: '#' },
  { title: 'Infinite Scroll', link: '#' },
  { title: 'Multi Typing', link: 'multi-typing' },
];
