export const challenges = [
  { title: "Accordion", link: "#/0/accordion", isNew: true },
  { title: "Counter", link: "#/1/counter" },
  { title: "Guess the number", link: "#" },
  { title: "Telephone formatter", link: "#" },
  { title: "Light & Dark mode", link: "#" },
  { title: "Toast Popup", link: "#" },
  { title: "Password Strength", link: "#" },
  { title: "Star Rating", link: "#" },
  { title: "Pixel Art", link: "#" },
  { title: "Color Spotter", link: "#" },
  { title: "Todo List", link: "#" },
  { title: "Tic-Tac-Toe", link: "#" },
  { title: "Chess board", link: "#" },
];
