export const challenges = [
  { title: "Accordion", link: "#/0/accordion" },
  { title: "Counter", link: "#/1/counter" },
  { title: "Star Rating", link: "#/2/star-Rating", isNew: true },
  { title: "Light Dark Mode", link: "#/3/light-dark-mode", isNew: true },
  { title: "Guess the number", link: "#" },
  { title: "Telephone formatter", link: "#" },
  { title: "Light & Dark mode", link: "#" },
  { title: "Toast Popup", link: "#" },
  { title: "Password Strength", link: "#" },
  { title: "Pixel Art", link: "#" },
  { title: "Color Spotter", link: "#" },
  { title: "Todo List", link: "#" },
  { title: "Tic-Tac-Toe", link: "#" },
  { title: "Chess board", link: "#" },
];
