export const challenges = [
  {
    title: 'Counter',
    link: '#/0/counter',
    difficulty: 'easy',
    developer: 'sadanandpai',
    tags: [],
  },
  {
    title: 'Accordion',
    link: '#/1/accordion',
    developer: 'NikhilJHA01',
    difficulty: 'easy',
    tags: [],
  },
  {
    title: 'Star Rating',
    link: '#/2/star-Rating',
    difficulty: 'easy',
    developer: 'NikhilJHA01',
    tags: [],
  },
  {
    title: 'Light Dark Mode',
    link: '#/3/light-dark-mode',
    difficulty: 'easy',
    developer: 'NikhilJHA01',
    tags: [],
  },
  {
    title: 'Guess the number',
    link: '#/4/Guess-the-number',
    difficulty: 'easy',
    developer: 'deepakrajkranti',
    tags: [],
  },
  {
    title: 'Telephone formatter',
    link: '#/5/telephone-formatter',
    difficulty: 'easy',
    developer: 'arpansaha13',
    tags: [],
  },
  {
    title: 'Toast Popup',
    link: '#/6/toast-popup',
    difficulty: 'medium',
    developer: 'deepu0',
    tags: [],
  },
  {
    title: 'Password Strength',
    link: '#/7/password-strength',
    difficulty: 'medium',
    developer: 'deepu0',
    tags: [],
  },
  {
    title: 'Todo List',
    link: '#/8/todo-list',
    difficulty: 'medium',
    developer: 'deepakrajkranti',
    tags: [],
    isNew: true,
  },
  {
    title: 'Investment Calculator',
    link: '#/9/investment-calculator',
    difficulty: 'medium',
    developer: 'insharahAyyubi',
    tags: [],
    isNew: true,
  },
  {
    title: 'File Explorer',
    link: '#/10/file-explorer',
    difficulty: 'hard',
    developer: 'sadanandpai',
    tags: [],
    isNew: true,
  },
  {
    title: 'Typeahead / Autocomplete (offline)',
    link: '#/11/autocomplete-offline',
    difficulty: 'hard',
    developer: 'deepu0',
    tags: [],
    isNew: true,
  },
  {
    title: 'Typeahead / Autocomplete (online)',
    link: '#/12/autocomplete-online',
    difficulty: 'hard',
    developer: 'deepu0',
    tags: [],
    isNew: true,
  },
];
