export const contributors = new Map([
  ['sadanandpai', { name: 'Sadanand Pai', pic: 'https://avatars.githubusercontent.com/u/12962887' }],
  ['NikhilJHA01', { name: 'Nikhil Jha', pic: 'https://avatars.githubusercontent.com/u/63518046' }],
  ['noorulaink00', { name: 'Noor Ul Ain Khan', pic: 'https://avatars.githubusercontent.com/u/65324193' }],
  ['deepu0', { name: 'Deepak Kumar', pic: 'https://avatars.githubusercontent.com/u/22304384' }],
  ['deepakRikhav', { name: 'Deepak Rikhav', pic: 'https://avatars.githubusercontent.com/u/97227284' }],
  ['arpansaha13', { name: 'Arpan Saha', pic: 'https://avatars.githubusercontent.com/u/82361490' }],
  ['deepakrajkranti', { name: 'Deepak Raj', pic: 'https://avatars.githubusercontent.com/u/88797436' }],
  ['insharahAyyubi', { name: 'Insharah Ayyubi', pic: 'https://avatars.githubusercontent.com/u/103804673' }],
  ['rashidtvmr', { name: 'Rashid', pic: 'https://avatars.githubusercontent.com/u/58169715' }],
  ['gauravsinhaweb', { name: 'Gaurav Sinha', pic: 'https://avatars.githubusercontent.com/u/75125943' }],
  ['ayush-dutt-sharma', { name: 'Ayush Dutt Sharma', pic: 'https://avatars.githubusercontent.com/u/73738613' }],
  ['dhanu084', { name: 'Dhanush Kiran', pic: 'https://avatars.githubusercontent.com/u/54932658' }],
  ['kumaratul60', { name: 'Atul Kumar Awasthi', pic: 'https://avatars.githubusercontent.com/u/53579888' }],
]);
