export const sentences = [
  'he turned in the research paper on friday otherwise he would have not passed the class',
  'plans for this weekend include turning wine into water',
  'the miniature pet elephant became the envy of the neighborhood',
  'as she walked along the street and looked in the gutter she realized facemasks had become the new cigarette butts',
  'he had unknowingly taken up sleepwalking as a nighttime hobby',
  'they got there early and they got really good seats',
  'david proudly graduated from high school top of his class at age 97',
  'he realized there had been several deaths on this road but his concern rose when he saw the exact number',
  'three generations with six decades of life experience',
  'her life in the confines of the house became her new normal',
  'he never understood why what when and where left out who',
  'truth in advertising and dinosaurs with skateboards have much in common',
  'its not possible to convince a monkey to give you a banana by promising it infinite bananas when they die',
  'he was willing to find the depths of the rabbit hole in order to be with her',
  'the estate agent quickly marked out his territory on the dance floor',
  'at that moment she realized she had a sixth sense',
  'the lyrics of the song sounded like fingernails on a chalkboard',
  'its not often you find a soggy banana on the street',
  'i have traveled all around africa and still havent found the gnu who stole my scarf',
  'although it wasnt a pot of gold nancy was still enthralled at what she found at the end of the rainbow',
  'honestly i didnt care much for the first season so i didnt bother with the second',
  'the balloons floated away along with all my hopes and dreams',
  'the anaconda was the greatest criminal mastermind in this part of the neighborhood',
  'he learned the hardest lesson of his life and had the scars both physical and mental to prove it',
  'he set out for a short walk but now all he could see were mangroves and water were for miles',
  'the spa attendant applied the deep cleaning mask to the gentlemans back',
  'the busker hoped that the people passing by would throw money but they threw tomatoes instead so he exchanged his hat for a juicer',
  'the irony of the situation wasnt lost on anyone in the room',
  'the bug was having an excellent day until he hit the windshield',
  'it would have been a better night if the guys next to us werent in the splash zone',
  'kevin embraced his ability to be at the wrong place at the wrong time',
  'she was amazed by the large chunks of ice washing up on the beach',
  'watching the geriatric mens softball team brought back memories of 3 yr olds playing tball',
  'he used to get confused between soldiers and shoulders but as a military man he now soldiers responsibility',
  'in hopes of finding out the truth he entered the oneroom library',
  'he found his art never progressed when he literally used his sweat and tears',
  'homesickness became contagious in the young campers cabin',
  'today i dressed my unicorn in preparation for the race',
];
